### ISSUE TITLE
Upgrade OpenLayers to version 3

### ISSUE THREAD

**Issue by stoqs** [stoqs/stoqs#222]
The client-side map plotting JavaScript library OpenLayers  is currently at version 2 in STOQS. 

We would like to upgrade to OpenLayers version 3 for several reasons. A primary reason is that OLv3 renders map imagery in a single div allowing addition of any kind of map data to the Spatial -> 3D view in the STOQS UI.

**Comment by MBARIMike** [comment]
There has been a lot of buzz about Leaflet and that it's easier to use than OpenLayers. It might be worth evaluating Leaflet before embarking on an OpenLayers 3 upgrade.

**Comment by MBARIMike** [comment]
Welcome @jingyang1991, @coparker, @dcalderon97, and @Discharg to the STOQS project!

**Comment by coparker** [comment]
Leaflet API documentation to be used when upgrading mapping components.
http://leafletjs.com/reference-1.3.0.html

Examples included on the leaflet site.
http://leafletjs.com/examples

**Comment by MBARIMike** [comment]
It looks like the team is leaning toward Leaflet. Can you briefly outline the rationale for making that decision?

Your project presentation mentions upgrading the 3D mapping component of the STOQS UI. To be clear, it's the 2D ("Map") component that this Issue is about. The "3D" tab in the UI uses the X3DOM Javascript library. It also needs updating, but that will be another Issue.

**Comment by dcalderon97** [comment]
Decision To Utilize Leaflet:
1. Lightweight and learning curve is not as steep as OpenLayers.
2. Leaflet has been gaining more traction as the mapping library to use.
3. Provides nicer documentation.
4. More code examples on the internet.

**Comment by coparker** [comment]
Meeting on 3/3/2018 to go over possible NFS install issues for windows systems as well as details such as the filepath for the file that we are going to be modifying as a team. (stoqs/stoqs/templates/stoqs/stoqsquery.html)

**Comment by MBARIMike** [comment]
Yes, that file is currently [stoqs/stoqs/templates/stoqs/stoqsquery.html](https://github.com/stoqs/stoqs/blob/03c18841b3c6fda5465604ed5565fb091e066098/stoqs/stoqs/templates/stoqs/stoqsquery.html)

**Comment by coparker** [comment]
Hey Prof McCann,
Could I get the instructions for the docker deployment listed here for use on windows?

**Comment by coparker** [comment]
Hey Prof. McCann,
I was wondering if you could explain the code between lines 5569 and 5589?

**Comment by MBARIMike** [comment]
Hi @coparker,

Sorry for the delay. Just seeing your comments now. 

See near the bottom of https://github.com/stoqs/stoqs/blob/master/README.md for production deployment using Docker. This is still WIP.

[Lines 5569-5589](https://github.com/stoqs/stoqs/blob/master/README.md) adds the colored KML-formatted "sensor track" layer to the map.

**Comment by coparker** [comment]
Hey @MBARIMike,

Do we need to migrate the code between lines 5596-5610 since they are throwing an exception in Openlayers? Also do we need to migrate the code between lines 5625-5649 since it was never fully implemented in the Openlayers deployment? There is also a large chunk of commented out code between lines 5652-5700 that the group is unsure of what to do with moving forward.

**Comment by dcalderon97** [comment]
Hey @MBARIMike 

I recently started to have an issue when trying to retrieve the test data, I deleted my install and started from a new install. Here is a full description of the error. 

`INFO 2018-04-07 02:32:47,503 DAPloaders.py process_data():1204 Adding altitude to the Measurements...
ERROR 2018-04-07 02:32:47,504 __init__.py addAltitude():1404 Cannot add altitude. Make sure file loaders/Monterey25.grd is present.
Traceback (most recent call last):
  File "loaders/loadTestData.py", line 85, in <module>
    cl.loadDorado(stride=1000)
  File "/vagrant/dev/stoqsgit/stoqs/loaders/CANON/__init__.py", line 144, in loadDorado
    plotTimeSeriesDepth=0.0)
  File "/vagrant/dev/stoqsgit/stoqs/loaders/DAPloaders.py", line 1600, in runDoradoLoader
    loader.process_data()
  File "/vagrant/dev/stoqsgit/stoqs/loaders/DAPloaders.py", line 1206, in process_data
    self.addAltitude(self.activity)
  File "/vagrant/dev/stoqsgit/stoqs/loaders/../loaders/__init__.py", line 1423, in addAltitude
    fh.close()
UnboundLocalError: local variable 'fh' referenced before assignment
loaders/loadTestData.py failed to load initial database; exiting test.sh.`

**Comment by MBARIMike** [comment]
@dcalderon97 : We moved the stoqs.mbari.org name to a new server and it's taken a while for the new IP address to migrate through DNS. Please try your `./test.sh CHANGME load noextraload` again; the updated DNS record should be propagated by now.

**Comment by dcalderon97** [comment]
@MBARIMike I tried the command but continue to have the same issue. I have the addAltitude function commented out so that I can continue working. Should I reinstall the site again or is there perhaps another fix?

**Comment by MBARIMike** [comment]
@dcalderon97 Does the command at [line 84 in test.sh](https://github.com/stoqs/stoqs/blob/634988836d973031aafb65832809beb17aaf5110/test.sh#L84) work on your system?
```
wget -q -N -O loaders/Monterey25.grd http://stoqs.mbari.org/terrain/Monterey25.grd
```
Try it without the -q option to see if there are any error messages.

**Comment by dcalderon97** [comment]
@MBARIMike this is the result of running the command by itself.  `WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2018-04-11 06:24:00--  http://stoqs.mbari.org/terrain/Monterey25.grd
Resolving stoqs.mbari.org (stoqs.mbari.org)... 134.89.2.40
Connecting to stoqs.mbari.org (stoqs.mbari.org)|134.89.2.40|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://stoqs.mbari.org [following]
--2018-04-11 06:24:00--  https://stoqs.mbari.org/
Connecting to stoqs.mbari.org (stoqs.mbari.org)|134.89.2.40|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18894 (18K) [text/html]
Saving to: ‘loaders/Monterey25.grd’

100%[======================================>] 18,894      --.-K/s   in 0s      

2018-04-11 06:24:01 (121 MB/s) - ‘loaders/Monterey25.grd’ saved [18894/18894]`

**Comment by MBARIMike** [comment]
The server hosting stoqs.mbari.org does a redirect to the secure https service. This is somehow causing a problem. Compare these two wgets:
```
(venv-stoqs) [vagrant@localhost tmp]$ wget -N -O loaders/Monterey25.grd http://stoqs.mbari.org/terrain/Monterey25.grd
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2018-04-12 17:57:24--  http://stoqs.mbari.org/terrain/Monterey25.grd
Resolving stoqs.mbari.org (stoqs.mbari.org)... 134.89.2.40
Connecting to stoqs.mbari.org (stoqs.mbari.org)|134.89.2.40|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://stoqs.mbari.org [following]
--2018-04-12 17:57:24--  https://stoqs.mbari.org/
Connecting to stoqs.mbari.org (stoqs.mbari.org)|134.89.2.40|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18894 (18K) [text/html]
Saving to: ‘loaders/Monterey25.grd’

100%[==================================================================================================================================>] 18,894      --.-K/s   in 0.001s

2018-04-12 17:57:25 (30.2 MB/s) - ‘loaders/Monterey25.grd’ saved [18894/18894]

(venv-stoqs) [vagrant@localhost tmp]$ wget -N -O loaders/Monterey25_s.grd https://stoqs.mbari.org/terrain/Monterey25.grd
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2018-04-12 17:57:42--  https://stoqs.mbari.org/terrain/Monterey25.grd
Resolving stoqs.mbari.org (stoqs.mbari.org)... 134.89.2.40
Connecting to stoqs.mbari.org (stoqs.mbari.org)|134.89.2.40|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28151652 (27M) [text/plain]
Saving to: ‘loaders/Monterey25_s.grd’

100%[==================================================================================================================================>] 28,151,652  7.86MB/s   in 3.5s

2018-04-12 17:57:46 (7.71 MB/s) - ‘loaders/Monterey25_s.grd’ saved [28151652/28151652]
```
And the file sizes:
```
(venv-stoqs) [vagrant@localhost tmp]$ ls -l loaders/
total 27512
-rw-rw-r--. 1 vagrant vagrant    18894 Apr 12 17:57 Monterey25.grd
-rw-rw-r--. 1 vagrant vagrant 28151652 Apr  7 00:46 Monterey25_s.grd
```
There's a problem with the redirect that I need to fix on the server. In the meantime pull from upstream to merge https://github.com/stoqs/stoqs/pull/699 into your working directory. It includes a change to use https to get the Monterey25.grd file.

**Comment by dcalderon97** [comment]
I reinstalled from scratch and everything works fine now.

**Comment by MBARIMike** [comment]
The redirect problem on the server has been fixed with [this commit](https://github.com/stoqs/stoqs/pull/701/commits/ae5d5f84723329698d3f4639a8efd85dc35c4432).

**Comment by dcalderon97** [comment]
@MBARIMike While looking into leaflet we realized it does not support retrieving single tiles, but a plugin does. The downside is that the plugin does not support redrawing the WMS layers. Is it more important to have the single tile option or the redrawing option? If so, which one would you like us to preserve?

**Comment by MBARIMike** [comment]
For now it’s more important to have the redrawing option. At some time I’d like to see a demonstration.

**Comment by MBARIMike** [comment]
A heads-up that I will need to modify [stoqs/stoqs/templates/stoqs/stoqsquery.html](https://github.com/stoqs/stoqs/blob/2d76e4a6f0b1b76ffea68cf205ca79107c0974c1/stoqs/stoqs/templates/stoqs/stoqsquery.html) soon as part of https://github.com/stoqs/stoqs/issues/552. I've tried to avoid touching that file so as to avoid potential merge conflicts. Is there a fork on GitHub where I can see the changes you've been making?

**Comment by dcalderon97** [comment]
Yes, here it is. https://github.com/dcalderon97/stoqs/tree/python3/stoqs/stoqs/templates/stoqs

**Comment by MBARIMike** [comment]
Yesterday I merged [this commit](https://github.com/stoqs/stoqs/commit/53d7d02c264a9a5554e75df2a6c4c42e2c3a0401) into master. In your working directory that you've [configured with the upstream remote](https://github.com/stoqs/stoqs/blob/master/CONTRIBUTING.md#setting-up-your-development-system) I suggest that you merge from upstream master:
```
git pull upstream master
```
so as to avoid potentially nasty future merge conflicts.
