### ISSUE TITLE
Install Failure

### ISSUE THREAD

**Issue by josephmfaulkner** [stoqs/stoqs#306]
### I attempted to install STOQS in a virtual environment by following the instructions in the README on the main page. I am using Vagrant 1.8.4 and VirtualBox 5.0.22 on Ubuntu 14.04. 
I ran the instructions in the readme: 
`curl "https://raw.githubusercontent.com/stoqs/stoqs/master/Vagrantfile" -o Vagrantfile
curl "https://raw.githubusercontent.com/stoqs/stoqs/master/provision.sh" -o provision.sh
vagrant up --provider virtualbox`

### During the installation, I noticed the following errors: 

`...
==> default:   Running setup.py clean for GDAL
==> default:   Failed building wheel for GDAL

...
==> default:   Running setup.py clean for netCDF4
==> default:   Failed building wheel for netCDF4

...
==> default:   ----------------------------------------
==> default:   Running setup.py bdist_wheel for pandas: started
==> default:   Failed cleaning build dir for netCDF4

...
==> default:   Running setup.py clean for scikit-learn
==> default:   Failed building wheel for scikit-learn\

...
==> default: Command "/home/vagrant/dev/stoqsgit/venv-stoqs/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-eisQWY/GDAL/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-4TdxIg-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/vagrant/dev/stoqsgit/venv-stoqs/include/site/python2.7/GDAL" failed with error code 1 in /tmp/pip-build-eisQWY/GDAL/
`

###After the setup, I proceeded to login to the  virtual environment and continue setup:

`
joseph@josephubuntu:~/STOQS$ ls
provision.sh  Vagrantfile
joseph@josephubuntu:~/STOQS$ vagrant ssh
/usr/bin/xauth:  file /home/vagrant/.Xauthority does not exist
[vagrant@localhost ~]$ ^C
[vagrant@localhost ~]$ ^C
[vagrant@localhost ~]$ logout
Connection to 127.0.0.1 closed.
joseph@josephubuntu:~/STOQS$ ls
provision.sh  Vagrantfile
joseph@josephubuntu:~/STOQS$ vagrant ssh -- -X   
Last login: Sat Jun 18 04:58:50 2016 from 10.0.2.2
[vagrant@localhost ~]$ cd ~/dev/stoqsgit && source venv-stoqs/bin/activate
(venv-stoqs) [vagrant@localhost stoqsgit]$ export DATABASE_URL=postgis://stoqsadm:CHANGEME@127.0.0.1:5432/stoqs
(venv-stoqs) [vagrant@localhost stoqsgit]$ ./test.sh CHANGEME
CREATE ROLE
ERROR:  database "stoqs" does not exist
CREATE DATABASE
ALTER DATABASE
Migrations for 'stoqs':
  0001_initial.py:
    - Create model Activity
    - Create model ActivityParameter
    - Create model ActivityParameterHistogram
    - Create model ActivityResource
    - Create model ActivityType
    - Create model AnalysisMethod
    - Create model Campaign
    - Create model CampaignLog
    - Create model CampaignResource
    - Create model InstantPoint
    - Create model MeasuredParameter
    - Create model MeasuredParameterResource
    - Create model Measurement
    - Create model NominalLocation
    - Create model Parameter
    - Create model ParameterGroup
    - Create model ParameterGroupParameter
    - Create model ParameterResource
    - Create model PermaLink
    - Create model PlannedDepthTime
    - Create model Platform
    - Create model PlatformResource
    - Create model PlatformType
    - Create model Resource
    - Create model ResourceResource
    - Create model ResourceType
    - Create model Sample
    - Create model SampledParameter
    - Create model SampledParameterResource
    - Create model SamplePurpose
    - Create model SampleRelationship
    - Create model SampleResource
    - Create model SampleType
    - Create model SimpleBottomDepthTime
    - Create model SimpleDepthTime
    - Add field samplepurpose to sample
    - Add field sampletype to sample
    - Add field resourcetype to resource
    - Add field resource to platformresource
    - Add field platformtype to platform
    - Add field resource to parameterresource
    - Add field nominallocation to measurement
    - Add field resource to measuredparameterresource
    - Add field measurement to measuredparameter
    - Add field parameter to measuredparameter
    - Add field resource to campaignresource
    - Add field resource to campaignlog
    - Add field resource to activityresource
    - Add field parameter to activityparameter
    - Add field activitytype to activity
    - Add field campaign to activity
    - Add field platform to activity
    - Alter unique_together for sampleresource (1 constraint(s))
    - Alter unique_together for samplerelationship (1 constraint(s))
    - Alter unique_together for sampledparameterresource (1 constraint(s))
    - Alter unique_together for sampledparameter (1 constraint(s))
    - Alter unique_together for resourceresource (1 constraint(s))
    - Alter unique_together for platformresource (1 constraint(s))
    - Alter unique_together for parameterresource (1 constraint(s))
    - Alter unique_together for parametergroupparameter (1 constraint(s))
    - Alter unique_together for measuredparameterresource (1 constraint(s))
    - Alter unique_together for measuredparameter (1 constraint(s))
    - Alter unique_together for campaignresource (1 constraint(s))
    - Alter unique_together for activityresource (1 constraint(s))
    - Alter unique_together for activityparameter (1 constraint(s))
Operations to perform:
  Synchronize unmigrated apps: staticfiles, messages, debug_toolbar, sites, allauth, django_extensions, crispy_forms
  Apply all migrations: account, sessions, admin, stoqs, auth, contenttypes
Synchronizing apps without migrations:
  Creating tables...
    Creating table django_site
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying account.0001_initial... OK
  Applying account.0002_email_max_length... OK
  Applying admin.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying sessions.0001_initial... OK
  Applying stoqs.0001_initial... OK
GRANT

Traceback (most recent call last):
  File "loaders/loadTestData.py", line 26, in <module>
    from CANON import CANONLoader
  File "/home/vagrant/dev/stoqsgit/stoqs/loaders/CANON/__init__.py", line 33, in <module>
    import DAPloaders
  File "/home/vagrant/dev/stoqsgit/stoqs/loaders/DAPloaders.py", line 50, in <module>
    from loaders import STOQS_Loader, SkipRecord, HasMeasurement, MEASUREDINSITU, FileNotFound
  File "/home/vagrant/dev/stoqsgit/stoqs/loaders/../loaders/__init__.py", line 38, in <module>
    from netCDF4 import Dataset
ImportError: No module named netCDF4
loaders/loadTestData.py failed to load initial database; exiting test.sh.

### Then, I logged into the server from a separate terminal and started the server: 

joseph@josephubuntu:~/STOQS$ vagrant ssh -- -X
Last login: Sat Jun 18 05:00:57 2016 from 10.0.2.2
[vagrant@localhost ~]$ cd ~/dev/stoqsgit && source venv-stoqs/bin/activate
(venv-stoqs) [vagrant@localhost stoqsgit]$ export DATABASE_URL=postgis://stoqsadm:CHANGEME@127.0.0.1:5432/stoqs
(venv-stoqs) [vagrant@localhost stoqsgit]$ stoqs/manage.py runserver 0.0.0.0:8000 --settings=config.settings.local
Performing system checks...

System check identified no issues (0 silenced).
June 18, 2016 - 05:06:43
Django version 1.8.10, using settings 'config.settings.local'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/core/urlresolvers.py", line 367, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/core/urlresolvers.py", line 367, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/core/urlresolvers.py", line 239, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/core/urlresolvers.py", line 246, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/core/urlresolvers.py", line 111, in get_callable
    if submod and not module_has_submodule(import_module(parentmod), submod):
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "stoqs/stoqs/views/__init__.py", line 29, in <module>
    from utils.MPQuery import MPQuery, MPQuerySet
  File "stoqs/utils/MPQuery.py", line 29, in <module>
    from loaders import MEASUREDINSITU
  File "stoqs/loaders/../loaders/__init__.py", line 38, in <module>
    from netCDF4 import Dataset
ImportError: No module named netCDF4
Internal Server Error: /
Traceback (most recent call last):
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/core/handlers/base.py", line 223, in get_response
    response = middleware_method(request, response)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/debug_toolbar/middleware.py", line 129, in process_response
    panel.generate_stats(request, response)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/debug_toolbar/panels/request.py", line 41, in generate_stats
    match = resolve(request.path)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/core/urlresolvers.py", line 521, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/core/urlresolvers.py", line 367, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/core/urlresolvers.py", line 367, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/core/urlresolvers.py", line 239, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/core/urlresolvers.py", line 246, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/core/urlresolvers.py", line 111, in get_callable
    if submod and not module_has_submodule(import_module(parentmod), submod):
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "stoqs/stoqs/views/__init__.py", line 29, in <module>
    from utils.MPQuery import MPQuery, MPQuerySet
  File "stoqs/utils/MPQuery.py", line 29, in <module>
    from loaders import MEASUREDINSITU
  File "stoqs/loaders/../loaders/../loaders/../loaders/__init__.py", line 38, in <module>
    from netCDF4 import Dataset
ImportError: No module named netCDF4
[18/Jun/2016 05:06:53] "GET / HTTP/1.1" 500 170200
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/middleware/common.py", line 75, in process_request
    urlresolvers.is_valid_path("%s/" % request.path_info, urlconf)):
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/core/urlresolvers.py", line 646, in is_valid_path
    resolve(path, urlconf)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/core/urlresolvers.py", line 521, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/core/urlresolvers.py", line 367, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/core/urlresolvers.py", line 367, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/core/urlresolvers.py", line 239, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/core/urlresolvers.py", line 246, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/django/core/urlresolvers.py", line 111, in get_callable
    if submod and not module_has_submodule(import_module(parentmod), submod):
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "stoqs/stoqs/views/__init__.py", line 29, in <module>
    from utils.MPQuery import MPQuery, MPQuerySet
  File "stoqs/utils/MPQuery.py", line 29, in <module>
    from loaders import MEASUREDINSITU
  File "stoqs/loaders/../loaders/../loaders/../loaders/../loaders/../loaders/__init__.py", line 38, in <module>
    from netCDF4 import Dataset
ImportError: No module named netCDF4
[18/Jun/2016 05:06:54] "GET /favicon.ico HTTP/1.1" 500 154101

###How do you have netCDF4 being installed on the system? 

`

**Comment by MBARIMike** [comment]
Hello Joseph,

Thanks for reporting this!

It looks like the provision.sh script is failing on building gdal and then fails to go on and finish the install of netcdf4. 

Maybe there's a new way to build gdal 2 from source now?

-Mike

**Comment by MBARIMike** [comment]
Note that to diagnose install problems it's useful to capture the output of the provision.sh script.

On MacOS this can be done with the `tee(1)` command thusly:

    vagrant up --provider virtualbox | tee provision.out

There may be a similar way to do this on Windows, maybe by redirecting the output:

    vagrant up --provider virtualbox > provision.out

**Comment by josephmfaulkner** [comment]
Ok, I'll log the output of the install and see what I can find.

**Comment by josephmfaulkner** [comment]
I'll take a look at the .out file: 
[provision.out.zip](https://github.com/stoqs/stoqs/files/322067/provision.out.zip)

**Comment by MBARIMike** [comment]
It looks like the install with gdal upgraded to version 2.1.0 in provision.sh succeeds. Please try provisioning a new VM after getting the newly merged provision.sh with:

    curl "https://raw.githubusercontent.com/stoqs/stoqs/master/provision.sh" -o provision.sh

**Comment by josephmfaulkner** [comment]
Just did that. I'm installing a new machine as we speak. The new .out file (and hopefully a working machine) will be done in a few hours.

**Comment by josephmfaulkner** [comment]
Doesn't look like that worked. 
"Failed building wheel for netCDF4"
Here are the .out files for that setup: 
[STOQS_SETUP_LOGS.zip](https://github.com/stoqs/stoqs/files/322367/STOQS_SETUP_LOGS.zip)

**Comment by MBARIMike** [comment]
Did you execute:

    cd ~/dev/stoqsgit && source venv-stoqs/bin/activate
    export DATABASE_URL=postgis://stoqsadm:CHANGEME@127.0.0.1:5432/stoqs
    ./test.sh CHANGEME
before trying to start the development server?

The test.sh script must be executed first because it creates the stoqsadm role in the database.

**Comment by josephmfaulkner** [comment]
I tried it again and got more issues: 

[provision.out.zip](https://github.com/stoqs/stoqs/files/332719/provision.out.zip)

**Comment by MBARIMike** [comment]
Seems to be the same issue as https://github.com/stoqs/stoqs/issues/312.

**Comment by MBARIMike** [comment]
Are you still having any issues with installation?

**Comment by josephmfaulkner** [comment]
I'll try again and report back.

**Comment by josephmfaulkner** [comment]
Good news. I ran the scripts on the main page and now it works!

**Comment by jonaszhang** [comment]
Hi @josephmfaulkner, I encountered the same problem. What do you mean by said " I ran the scripts on the main page..." Would you show us the details?

**Comment by chandna70** [comment]
Hi @MBARIMike , I have the problem about install STOQS via Docker, could you help me? I've been done for `docker-compose up`, as the result is error at the localhost.
