### ISSUE TITLE
problem executing uctdToNetcdf.py or pctdToNetcdf.py

### ISSUE THREAD

**Issue by duane-edgington** [stoqs/stoqs#478]
I am trying to generate netCDF files from MBARI uctd and pctd files. When I run scripts that call uctdToNetcdf.py or pctdToNetcdf.py I get the following errors:

(venv-stoqs)[stoqsadm@kraken toNetCDF]$ ./makeRCuctdNetCDF_os2017.sh
odssadm@odss.mbari.org's password: 
receiving incremental file list
uctd/
uctd/.DS_Store
uctd/00917plm01.asc
uctd/00917plm01.hdr
uctd/00917plm01.nc

sent 91 bytes  received 92471 bytes  20569.33 bytes/sec
total size is 92175  speedup is 1.00
Processing Sea-Bird .asc and .hdr files from directory 'uctd' with pattern '*.asc'
sb_file = uctd/00917plm01.asc
Traceback (most recent call last):
  File "./uctdToNetcdf.py", line 321, in <module>
    pw.process_files()
  File "./uctdToNetcdf.py", line 44, in process_files
    self.process_seabird_files()
  File "./uctdToNetcdf.py", line 113, in process_seabird_files
    self.write_ctd(sb_file)
  File "./uctdToNetcdf.py", line 231, in write_ctd
    self.time = self.ncFile.createVariable('time', 'float64', ('time',))
  File "/opt/stoqsgit_dj1.8/venv-stoqs/lib/python2.7/site-packages/pupynere.py", line 199, in createVariable
    data = empty(shape_, dtype=dtype_)
TypeError: data type ">d8" not understood
odssadm@odss.mbari.org's password: 
00917plm01.nc                                                                                                           100%  548     0.5KB/s   00:00    
(venv-stoqs)[stoqsadm@kraken toNetCDF]$ 

This has a feeling of deja vecu all over again but I can't remember the fix.

I am stuck...

**Comment by duane-edgington** [comment]
I had a memory that this problem came up before, and that I had a workaround implemented on my development system. Indeed, I found that I could successfully run the programs on my development system, though not on production system kraken. So, I am no longer stuck. However, we do still have the problem that others would hit on the production code.

**Comment by MBARIMike** [comment]
Yes, this problem comes from pupynere not keeping up with updates to numpy. There is a patch that can be made, but a more permanent solution would be better. In other netcdf generation code I've found that netCDF4 can be a drop-in replacement for pupynere, e.g. replace:

```python
from pupynere import netcdf_file
...
self.ncFile = netcdf_file(out_file, 'w')
...
```

with:

```python
from netCDF4 import Dataset
...
self.ncFile = Dataset(out_file, 'w')
...
```
It'd be good to remove pupuynere completely as a STOQS requirement so that we can more easily upgrage from Legacy Python this year.

**Comment by MBARIMike** [comment]
@duane-edgington Is this still a problem?
