### ISSUE TITLE
STOQs on AWS

### ISSUE THREAD

**Issue by mmerrifield** [stoqs/stoqs#484]
Hello all - I've posted this to stoqs-discuss as well, any tips are much appreciated

Hello - 

Has anyone had experience or success installing STOQS on AWS? If so can you recommend an AMI or configuration necessary?

I'm currently running an Ubuntu 16.04 instance and have gotten Vagrant and VirtualBox installed but getting the following error when running vagrant up.  And FWIW I've turned accelerated3d off in Vagrantfile

_There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "b00093d1-eadb-4246-ad08-2a4d40436455", "--type", "headless"]
Stderr: VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)

VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole__

**Comment by MBARIMike** [comment]
A response was [made on the stoqs-discuss mail list](https://groups.google.com/forum/#!topic/stoqs-discuss/u0FcqNWg0QA):

```
Hello Matt,

AFAIK no one has installed STOQS on AWS.

Is it possible to get a CentOS 7 AMI? If so, then you may be able to simply run the provision.sh script on it.

STOQS will work on Ubuntu (Travis-CI uses an Ubuntu Docker image), though provision.sh currently support only the CentOS package manager commands.

Please let us know how things go on AWS. It would be a great option for those who don't have access to their own server infrastructure.

Cheers,
Mike
```

**Comment by mmerrifield** [comment]
Hi Mike - CentOS 7 should not be a problem and good to hear about Ubuntu, I will give that a go and report back here.

Other thing I'm wondering is what the graphics capabilities of the server need to be - do you have any sense or specs?

Thanks much!

**Comment by MBARIMike** [comment]
Standard STOQS needs just basic server capabilities. With the addition of MB-System to the standard desktop Vagrant installation there is a desire to now have OpenGL support (see issue https://github.com/stoqs/stoqs/issues/450), but that is not needed for an AWS instance.

**Comment by mmerrifield** [comment]
UPDATE: I have CentOS 7 running on an AWS instance
Successfully installed stoqs but getting the following errors when I run test.sh.  Don't know if these are a big deal, I can successfully start the development server, but unable to see stoqs at http://my.ip.address:8000

any intel is appreciated - thanks!

_Unit tests...
Creating test database for alias 'default'...
......................................
----------------------------------------------------------------------
Ran 38 tests in 25.427s

OK
Destroying test database for alias 'default'...
Functional tests with development server running as pid = 18750 ...
Creating test database for alias 'default'...
EEEEEEE
======================================================================
ERROR: test_campaign_page (stoqs.tests.functional_tests.BrowserTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./stoqs/tests/functional_tests.py", line 50, in setUp
    self.browser = webdriver.Firefox(profile)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 140, in __init__
    self.service.start()
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 


======================================================================
ERROR: test_contour_plots (stoqs.tests.functional_tests.BrowserTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./stoqs/tests/functional_tests.py", line 50, in setUp
    self.browser = webdriver.Firefox(profile)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 140, in __init__
    self.service.start()
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 


======================================================================
ERROR: test_dorado_trajectory (stoqs.tests.functional_tests.BrowserTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./stoqs/tests/functional_tests.py", line 50, in setUp
    self.browser = webdriver.Firefox(profile)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 140, in __init__
    self.service.start()
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 


======================================================================
ERROR: test_m1_timeseries (stoqs.tests.functional_tests.BrowserTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./stoqs/tests/functional_tests.py", line 50, in setUp
    self.browser = webdriver.Firefox(profile)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 140, in __init__
    self.service.start()
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 


======================================================================
ERROR: test_query_page (stoqs.tests.functional_tests.BrowserTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./stoqs/tests/functional_tests.py", line 50, in setUp
    self.browser = webdriver.Firefox(profile)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 140, in __init__
    self.service.start()
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 


======================================================================
ERROR: test_share_view_timeseries (stoqs.tests.functional_tests.BrowserTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./stoqs/tests/functional_tests.py", line 50, in setUp
    self.browser = webdriver.Firefox(profile)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 140, in __init__
    self.service.start()
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 


======================================================================
ERROR: test_share_view_trajectory (stoqs.tests.functional_tests.BrowserTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./stoqs/tests/functional_tests.py", line 50, in setUp
    self.browser = webdriver.Firefox(profile)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 140, in __init__
    self.service.start()
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 


----------------------------------------------------------------------
Ran 7 tests in 7.647s

FAILED (errors=7)_

**Comment by mmerrifield** [comment]
UPDATE: I have CentOS 7 running on an AWS instance
Successfully installed stoqs but getting the following errors (7 in total - just pasted first one) when I run test.sh, looks like an issue with geckodriver?  I can successfully start the development server, but unable to see stoqs at http://my.ip.address:8000

any intel is appreciated

ERROR: test_campaign_page (stoqs.tests.functional_tests.BrowserTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./stoqs/tests/functional_tests.py", line 50, in setUp
    self.browser = webdriver.Firefox(profile)
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 140, in __init__
    self.service.start()
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by MBARIMike** [comment]
Those 7 errors are likely from the stoqs/stoqs/tests/functional_tests.py script which requires Firefox and an X-Server setup. That may require additional steps to configure on an AWS instance.

There might be a firewall issue with getting to port 8000 from outside. Can you test whether the development server is accessible directly from the instance?

```
curl http://localhost:8000
```

**Comment by stoqs** [comment]
Followed up with https://github.com/stoqs/stoqs/issues/833.
